Added clarity and option to cancel AddMovie
mootjso/Fuji_Films pull request #85
Opened 2023-11-22 10:10 UTC by xSha14

2023-11-22 10:13 UTC, mootjso submitted a review, later dismissed
Bekeken zo ver ik het zag, zag het er goed uit :)

2023-11-22 10:18 UTC, mootjso requested changes
Ziet er goed uit!
Zoals we hadden besproken zet er een check in om te kijken als de input de id is van een film die al bestaat.

2023-11-23 08:14 UTC, jorisgoeree commented
![image](https://github.com/mootjso/Fuji_Films/assets/144028306/32f28cdf-0d7b-4d5e-ab51-055b8d4deacf)
Klopt het dat je minstens 2 genres moet kiezen?

2023-11-23 08:17 UTC, jorisgoeree commented
> ![image](https://user-images.githubusercontent.com/144028306/285133223-32f28cdf-0d7b-4d5e-ab51-055b8d4deacf.png) Klopt het dat je minstens 2 genres moet kiezen?

Hij checkt hier of het aantal genres invult al een ID is voor een bestaande film. Dus vul ik 1 in dan en er is al een film met ID 1 dan kom ik hier niet langs, als ik 22 invul wel, omdat die ID nog niet bestaat.

2023-11-23 08:18 UTC, xSha14 commented
Dat is niet de bedoeling nee, ik zal even kijken waardoor het komt

On Thu, Nov 23, 2023, 09:14 jorisgoeree ***@***.***> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/144028306/285133223-32f28cdf-0d7b-4d5e-ab51-055b8d4deacf.png>
> Klopt het dat je minstens 2 genres moet kiezen?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mootjso/Fuji_Films/pull/85#issuecomment-1823958264>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALCZBABUC2FH7UGCMD5DDYLYF4AXHAVCNFSM6AAAAAA7V6Y25OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRTHE2TQMRWGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-23 08:26 UTC, xSha14 commented
> > ![image](https://user-images.githubusercontent.com/144028306/285133223-32f28cdf-0d7b-4d5e-ab51-055b8d4deacf.png) Klopt het dat je minstens 2 genres moet kiezen?
> 
> Hij checkt hier of het aantal genres invult al een ID is voor een bestaande film. Dus vul ik 1 in dan en er is al een film met ID 1 dan kom ik hier niet langs, als ik 22 invul wel, omdat die ID nog niet bestaat.

Check nu eens, denk dat het nu gefixt is

2023-11-23 08:28 UTC, jorisgoeree commented
> > > ![image](https://user-images.githubusercontent.com/144028306/285133223-32f28cdf-0d7b-4d5e-ab51-055b8d4deacf.png) Klopt het dat je minstens 2 genres moet kiezen?
> > 
> > 
> > Hij checkt hier of het aantal genres invult al een ID is voor een bestaande film. Dus vul ik 1 in dan en er is al een film met ID 1 dan kom ik hier niet langs, als ik 22 invul wel, omdat die ID nog niet bestaat.
> 
> Check nu eens, denk dat het nu gefixt is

Ja genres is nu gefixt.
![image](https://github.com/mootjso/Fuji_Films/assets/144028306/2e8cd064-7c6a-4004-9ba5-013928d74ae3)
Kun je nog zorgen dat cursor niet zichtbaar is op dit scherm?

2023-11-23 08:34 UTC, xSha14 commented
> > > > ![image](https://user-images.githubusercontent.com/144028306/285133223-32f28cdf-0d7b-4d5e-ab51-055b8d4deacf.png) Klopt het dat je minstens 2 genres moet kiezen?
> > > 
> > > 
> > > Hij checkt hier of het aantal genres invult al een ID is voor een bestaande film. Dus vul ik 1 in dan en er is al een film met ID 1 dan kom ik hier niet langs, als ik 22 invul wel, omdat die ID nog niet bestaat.
> > 
> > 
> > Check nu eens, denk dat het nu gefixt is
> 
> Ja genres is nu gefixt. ![image](https://user-images.githubusercontent.com/144028306/285137474-2e8cd064-7c6a-4004-9ba5-013928d74ae3.png) Kun je nog zorgen dat cursor niet zichtbaar is op dit scherm?

done

2023-11-23 14:03 UTC, merged